var emailcontent = document.getElementById('emailcontent');

var typewriter = new Typewriter(emailcontent, {
  loop: true,
  delay: 25,
});

typewriter
  .typeString('<div class="typed-out">Oct 29, 2020, 6:09PM</div><br>')
  .pauseFor(300)
  .typeString('Hi Hans,<br><br>')
  .typeString('My name is Emily Dinh and I am a member of Alpha Phi Omega at Virginia Tech! I am a junior studying Graphic Design and hope one day to work in branding or UX/UI design. What was your major at Virginia Tech?<br><br>')
  .typeString('I wanted to express my sincere gratitude regarding your sponsorship! Being away from home and being in college is an expensive challenge and I am extremely thankful for your generosity and kindness.<br><br>')
  .typeString('Your donation is simply another reminder that APO is the type of organization that has a lasting impact on the rest of your life. Here is some background to my APO journey thus far. My very first semester at Virginia Tech was extremely lonely. I went from class to the library, to my dorm. Feeling homesick, I thought about transferring home. However, my aunt pushed me to stay for a year and encouraged me to put myself out there. Therefore, in the spring, I began to look for a club to join. But I did not want to join just any club, I was looking to do service and build meaningful friendships; make Virginia Tech home in a way. Thankfully, I found APO and the rest is history.<br><br>')
  .typeString('I am constantly thankful for everything APO has given me. How did you get involved with APO?<br><br>')
  .typeString('As things have gone virtual, things have been very different, especially service opportunities. Some of my favorite projects are Giving Tree, a food pantry, and Card-Making around the holidays! I am always looking to try new projects though! What kind of projects did they offer when you were a member? Were there any projects that were your favorite?<br><br>')
  .typeString('Best,<br><br>Emily Dinh<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Nov 5, 2020, 1:28AM</div><br>')
  .pauseFor(300)
  .typeString('Hi Emily!<br><br>')
  .typeString('(Insert cheerful smile here) :-D THANK YOU for reaching out in the way that you did, genuinely yourself with your story to tell and questions about me. THAT ROCKED!<br><br>')
  .typeString('I am going to start by saying: I kid you not that I LAUGHED OUT LOUD when you said, "I hope you will forgive me for the lengthy email!" Forgive me! BUT I REALLY DID LAUGH OUT LOUD! Please allow me to explain. It will make sense.<br><br>')
  .typeString('I am known to be INSANELY verbose, especially in my many writings, to friends, at work, for the San Francsico HOKIES  Alumni Association, and more. My family, friends, and workers all joke about it at times. I have to remind myself of my audience and often edit myself often of my own verbosity, such as putting an executive summary at the top of my messages for the short readers, or cutting out long swaths of things I REALLY wanted to say in both a glorified nonlinear multiple nuance stream of consciousness and a linear well organized complete detail manual as both an artist AND and engineer would do... at the same time. Got all that?<br><br>')
  .typeString('(Side note, my mother was an Opera Singer and my dad and Electrical Engineer. So now you know the constant struggle between the artist and engineer that goes on in my mind. I studied Electrical Engineering at Tech.  And years later tend to think of people in the Architect world as natural brains with both artist and engineer in them... Probably should have pursued that. :-)')
  .typeString('See where I am going with this?<br><br>')
  .typeString('So in my reading your email and thinking "She is spot on, well  spoken, to the point, and I am really enjoying reading this." AND THEN reading your "I hope you will forgive me for the lengthy email" I HAD TO LOSE IT LAUGHING, knowing you do not know me and the absolute cosmic total irony of the fact that it is ME who SHOULD and probably WILL  say "I hope you will forgive me for the lengthy email" to YOU!<br><br>')
  .typeString('My siblings would be laughing too if they heard this story. OK I hope that gave you a laugh. REALLY! That made my day! Now to your email.<br><br>')
  .typeString('Feel free to call me "Hans." I appreciate the respect of "Mr."  as one who is an "adult"... to some degree. But being number four of five kids in a large family, I am figuratively everyone elses little brother, and, volunteering with kids a couple decades (entertainment director at Muscular Dystrophy Association Summer Camp), I generally maintain the mentality of around nine years old.  So the upshot of this is that  figuratively my little sister is "older (read between the lines... "more mature") than me." :-D  Bottom line is growing up this way and maintaining this way of looking at things keeps me in a mode of humility, regardless of status. So it helps me be more approachable and genuine with people from all walks of life.  If all that makes sense.<br><br>')
  .typeString('College of Architecture and Urban Studies. WHOO HOO!<br><br>')
  .typeString('You said, "... another reminder that APO is the type of organization that has a lasting impact on the rest of your life." Well I was blessed to have people like this in my life while at Tech. OK here is a small snippet of a longer story of my connection to the College of Architecture:<br><br>')
  .typeString('While at Tech, I lived in the house of a former Architecture Professor, Henry Wiss. He and his wife Dorothy had traveled the world twice over during his tenure, and they sponsored many international students. I was not an international student, but came to Virginia Tech after Henry had a stroke, and Dorothy needed someone to live at the house to take care of the property as if it was their own. Over the four years I lived at "Wiss Acres" as it was nicknamed, Dorothy had many many visitors from all over the world that she introduced me to. Back then the extent of my travel and cultural awareness was the drive from Upstate New York to Blacksburg, Virginia, and knowing I had crossed the Mason-Dixon line somewhere in between. And then Dorothy introduced  me to many people from places I had only heard about. And she revealed to me Henrys slide collection of over 20,000 photos taken all over the world. Not a trivial feat back then.<br><br>')
  .typeString('Dorothy always used to say, "There is no money better spent than on travel." So why did it take me almost another decade to get this?<br><br>')
  .typeString('One of the HUGE reasons for where I am now,  the people I know, my career, my path, the San Francisco Bay Area... is due to Dorothy and the many connections she helped me form, lessons on how to meet and interact with many different people from all over the world, and the mindset that there was a huge world out there to discover. So again, WHY DID IT TAKE ME SO LONG? Well I finally got around to that travel thing and the light bulb finally went on.<br><br>')
  .typeString('I stayed with Dorothy for free, her attitude, and mine, being "take care of people and ask them to pay it forward." It is a good attitude IMHO as it promotes service that keeps promoting service. :-)<br><br>')
  .typeString('****<br><br>')
  .typeString('Your story about your first semester. Oh wow. Thank you for being so open right up front. You have pushed many story buttons on me whereby I can reciprocate/empathize at length,  and then say... here it comes,  "I hope you will forgive me for the lengthy email" (Sorry I am gonna keep that one up. It is too good not to. I am laughing again.)<br><br>')
  .typeString('My first week at Virginia Tech started with watching my parents drive off with my mom tearing up. I was going to school 500 miles from home. So this was it! Not going to see my parents at least until Thanksgiving. On the drive there we made a mini vacation out of it, and at some point I hurt my foot to the degree that it felt broken (pinched nerve). I spent my first week on crutches, not knowing anyone, (not entirely true as I had friends who were two years ahead, but not physically at school yet), and basically lost.<br><br>')
  .typeString('I am gregarious so eventually got to making connections and friends. Even then it was a challenge as "friendships" can initially be the result of simply being scared and bonding to nearby people without really knowing who they are. Then later when you get to know them you realize you really do not want to be with them for whatever reason: some of them are not such great people, while others are but you have nothing in common. I described my freshman year in the all male dorm (OShag) as us guys being "a bunch of baby monkeys who have just left their mothers NOW clinging to each other simply because they are scared..." and they show only their good sides or pretend to be someone they are not because they are desperate for acceptance from each other. But that mask can only hold out for so long, as it takes so much energy to keep up.  And one day they start to reveal their true selves, which THEN acts as a good filter as they realize that perhaps the other baby monkeys are NOT the people they want to be hanging with. So as they all become more real with themselves and others (not all do) they branch out, which is good!<br><br>')
  .typeString('I remember when I changed roommates in the winter that the RA said something along the llnes of, "this is the time when everyone wants to change roommates because now they have gotten to know each other."<br><br>')
  .typeString('Often best friends in life are NOT the people you say "WOW! We are gonna be best friends!" (as some of us did in the dorm in our initial weeks) but instead people you just start spending time with doing something in common and then months, even years later, you just realize you have been friends all along. The transition can be difficult when a sudden change throws you into into a completely new place.  Loneliness ensues, and perhaps trust/fear keep you isolated.  The branching out and developing connections/friendships has to happen organically, in stages, not be forced, and eventually you have a network of good peeps. And the awareness that you can establish this again when another major life change comes along.<br><br>')
  .typeString('GLAD your Aunt pushed you! And encouraged you to put yourself out there!!!!! Discovery! Discovery! Self Discovery! :-)<br><br>')
  .typeString('I too joined APO for the same reasons you did. I had the choice to join a social fraternity and had a bunch of friends (to this day) that tried to get me to join theirs. But I was adamant that my first choice would be a service organization, and THEN I would consider joining a social organization later on. APO became my life. Oh and I was a student. HA HA! SO I never got around to a social fraternity.<br><br>')
  .typeString('The challenge of virtual and being sheltered at home... I can but cannot imagine... (well can but want to stick my head in the sand) for what you all are going through.<br><br>')
  .typeString('For me in the work world, I traveled so much that it has been nice NOT traveling for a bit and being able to have focused contiguous time at home. But then there is the blur between work and home life and the ambiguity thereof that creates a feeling of having to constantly be on. I have a friend out here who is a 19 year old college student and we compare notes on our stress, her classes and work work work, and my work  and work work work. Different worlds, but ability to see eye to eye on the challenges and stress thereof, AND then add the shelter at home layer. As I have said to many friends, "For those of us who are good at entertaining ourselves in our own minds, and do, NOW is the time to help others do the same." There are many people who are extroverts who need the people time, albeit virtual. And then there are the introverts, who can be quite OK with the alone time, be it sheltered at home, or out running, biking, hiking, whatever.<br><br>')
  .typeString('In college though, it is SOOO vitally important to have a TON of interactions and learn from them all, students, professors, clubs, the community, etc. This is your opportunity to build not just an awesome set of  friends and stories that will last for life, but also a network that will support you for life and give you the ability to support others. So yeah, this shelter at home thing stinks for now.  The virtual thing is challenging, BUT think of it this way, had this happened 20-30 years ago and you were a student, there would be no virtual anything. It would be go home and stay there and wait it out. So thank goodness we have SOME form of communication whereby we can maintain our connections and even service in more innovative and creative ways. :-)<br><br>')
  .typeString('OK so asking me about service projects is a loaded question!<br><br>')
  .typeString('Not to boast in any way, but I was the service VP one year when we had 100+ actives, 30+ service projects, and received the National Award for the chapter with the best service program. I DO NOT take any credit for that. (That is why I am saying not boasting). I simply was in the right place at the right time with a large group of very dedicated people and had the honor of being able to serve them with all my energy, both whacky and verbose and serious and to the point.  It was an incredible experience that was both insanely exhausting and nerve wrecking and also exhilarating... rejuvenating .. on a weekly basis.  So many opportunities to serve, so many lessons to learn, and so many people to meet across Tech, Blacksburg, Roanoke, The New River Valley, etc.<br><br>')
  .typeString('I guess I could say my favorite project was the one I started: the Road Racing Chair Position, whereby brothers would help organize volunteer support for local road races in Blacksburg and Christiansburg, including proactively working with The Blacksburg Striders, VT and Town Police, and more to help them be successful. I ended up being President of the Blacksburg Striders one year, and race director for the Blacksburg Classic, so it was a natural fit to pull APO brothers in. But I took it a step further and intentionally invited members of other campus service groups and deliberately positioned volunteers along the course such that brothers would not be with brothers, but with other service group members, so they could meet and mingle for the first time while serving together. My "ulterior motive of sorts" for a bigger picture was eventually to  try to form the "Student Service Learning Council" with leaders of each major service organization on campus (similar to Panhellenic council for Fraternities and Sorrorities). I never was able to get this to take off and I bit off way more than I could chew by  spreading myself WAY TO THIN (as is my propensity...only 24 hours in the day). BUT I was able to leverage the work we did organizing the student service organization leaders to tie it into the start of Virginia Techs first Service Learning Center, which eventually became VT Engage. So a seed in the ground with a little water, but that was enough to contribute.<br><br>')
  .typeString('Opportunities like the above abound for you and the other brothers.<br><br>')
  .typeString('How is that for a short answer to your question?<br><br>')
  .typeString('OK BY NOW YOU KNOW what I am going to say next.....<br><br>')
  .typeString('Wait for it....<br><br>')
  .typeString('WAIT FOR IT!!!!<br><br>')
  .typeString('"I hope you will forgive me for the lengthy email!"<br><br>')
  .typeString('(pause for effect here)<br><br>')
  .typeString('BWAAAA HAHAHAAHAHAHAA!<br><br>')
  .typeString('You better be laughing! HEE HEE! ;-)<br><br>')
  .typeString('OK NOW for the DISCLAIMER:<br><br>')
  .typeString('1. I hope you enjoyed my majorly verbose waxing poetic response and it benefitted you some way. ;-)<br><br>')
  .typeString('2. I ABSOLUTELY DO NOT EXPECT YOU TO RESPOND WITH SAME VERBOSITY/INTESITY! ZERO EXPECTATION! NO OBLIGATION! NO PRESSURE! NADA! NIL! Sometimes people get worried/freaked with my lengthy high energy communications, one joke being, "The email flew off my screen and around the room a few times before it landed where i could read it" and then feel like they have to write ten pages to match mine. And then feel guilty when they do not. Heck I feel guilty when I get behind and have to stop answering emails for a bit. So yeah, none of that. Just enjoy!<br><br>')
  .typeString('3. Not all my emails are this long. No really! :-P  ;-)<br><br>')
  .typeString('4. Simply read, enjoy, and feel free to respond as you would in whatever way and whatever timeframe. Holler as you will, even if you just need to say "AAHHHHHHHHHHHHHHHHHHHH! It is FINALS WEEK! AHHHHHHHHH! I AM SOOO STRESSEDDDDDDDDDDDDDDDDD!" and then disappear for another three months. HA HA! ;-) Know you have an ear over hear on the "Left Coast" I may respond, "AAHHHHHHHHHHHHHH! There is a major project at work that is driving me up the wall! I AM SOOO STRESSSEDDDDDDDDDDDDDDDDD!" and then disappear for another three months.<br><br>')
  .typeString('You got tons to focus on there and are undoubtedly insanely busy. I am insanely busy too at times, but occasionally find the time to have these long winded creative outbursts with friends and family because it can be both FUN and helpful for all, even if it does occasionally drive them up the wall. HA HA! By the same token I also disappear for lengths of time due to being busy.<br><br>')
  .typeString('So yes, there it is. You probably were not expecting this response. BUT deserved it! I really appreciate that you wrote, what you said genuinely, and how you wrote it, so felt compelled to respond in full crazy "HOKIE Hans" style without holding back in hopes you enjoy and get something out of it as well.<br><br>')
  .typeString('In LFS, AND Brotherhood,<br><br>')
  .typeString('Mr. Bern... I MEAN  (ha ha!)<br><br>')
  .typeString('Hans<br><br>')
  .typeString('"HOKIE Hans"<br><br>')
  .typeString('VT ZB EE 93  Weeeeeeeeeee!<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Dec 7, 2020, 2:16AM</div><br>')
  .pauseFor(300)
  .typeString('Hi Hans,<br><br>')
  .typeString('First of all, I HAVE to apologize for my late response. School has quite literally taken over my life. In my high school AP Euro class, my teacher gave us all superlatives before our AP exam and mine was, of course, "most likely to need a stress ball." Typical. I tend to get stressed out and go into full hibernation mode so again, I apologize for the late reply!<br><br>')
  .typeString('Secondly, I am glad that you were able to get a good laugh from my email!! Being completely honest, I am an EXTREME oversharer and talker so in my last email, I actually had to hold myself back a LOT, as I was hoping not to overwhelm you. So I had to laugh a little bit at myself as well.<br><br>')
  .typeString('Thank you SO much for your email. I loved getting the opportunity to get to know you!! I am known for my extremely thorough stories that take about a hundred different detours, so that is, arguably, something to be excited about hahah!<br><br>')
  .typeString('So to start off, I wanted to address some things you talked about! I LOVE that you see yourself as both an engineer and an artist! My mom was a math major, my dad was an engineering major, and my sister majored in electrical engineering too!!! So as a kid in a very heavy STEM based family, I have always felt a little different than the rest of my family, but love what I do a lot and I am very grateful for my parents and their support!<br><br>')
  .typeString('I am infinitely jealous of your big family! My sister and I have an 8 year age gap which led us to fight, A LOT, as kids. But now, she is my best friend! While there is only the two of us, I love how close we are. Kind of upset though since both of my parents came from large families - my dad has 3 siblings, my mom had 5! Therefore, my extended family is extremely large. On my moms side, I am the baby, my closest cousin is 4 years older than me. So growing up with people older than me, I feel like I matured very quickly - though to be fair you would have to just take my word for it lol!<br><br>')
  .typeString('Anyways, I loved your story about your experience in the College of Architecture and Urban Studies. That is so cool! I cannot even imagine. Side note - upstate NY? Which part? When my mom came to the states, her family settled in Buffalo! She actually went to SUNY Buffalo!<br><br>')
  .typeString('Back to the original story lol! I love that quote about traveling. As someone who has never left the east coast, I know that there is so much left to see. A big bucket list item for me is to live in a van and drive cross country. While this is a difficult feat, it is always worth aspiring for something, who knows how much I can accomplish.<br><br>')
  .typeString('The idea of paying it forward is not foreign to me. My grandfather always taught my dad and eventually me that the generosity and kindness you show others will come back around. One day, I will have to tell you the story of how my grandpas life was changed - and indirectly mine - by the generosity of others. That is one of many reasons that I serve as well. The reason my family is where we are today is a direct result of the generosity of others and I can never forget that.<br><br>')
  .typeString('****<br><br>')
  .typeString('I cannot imagine going away for school so far. It is about a 5 hour drive from where I live and that is already too much for me. As a kid, I always knew I wanted to go away for college but the actual moment watching my parents drive away had me crying, hoping for one more meal together.<br><br>')
  .typeString('I totally agree. Proximity is definitely a motivator for making friends. It took me a whole semester to even make friends with the girls across the hall! But one of my best friends at school is a friend from home. There is something comforting about having people from home around you. That is why I am so thankful for APO. APO was a sort of home away from home and I have met some of the best people I have ever met. I am thankful constantly for their friendship and the memories I have made.<br><br>')
  .typeString('When I went to the APO interest meeting, I almost left, intimidated by the amount of people and overwhelmed by everything. I never considered myself a huge believer in fate but if I had not seen two girls from my hall there, I could have walked away from APO and who knows what my life would be like now.<br><br>')
  .typeString('Speaking of how life is right now, I agree. It is such a strange time. As an extroverted introvert, I think overall, I am doing just fine. I know it is rare to hear people say that but I have found peace in being home with my family and letting myself enjoy my alone time. Of course, I have been going stir crazy at times, but overall, being home is good for me.<br><br>')
  .typeString('I LOVED the humble brag about your time as service VP! Those accomplishments demand to be shared and bragged about, I am super impressed! The Road Racing program sounds so fun! I suppose I forgot to mention in my last email that I currently serve on the Exec board as well as the Communications Secretary!!! Fun fact: My APO twin is actually the Service Vice President as well!! As a timid freshman, I never imagined in any universe that I would serve on the exec board but am so thankful for this experience to lead and serve my brothers!<br><br>')
  .typeString('As it feels like a tradition at this point... sorry for the lengthy email! LOL.<br><br>')
  .typeString('I appreciate the disclaimer greatly. In response:<br><br>')
  .typeString('1. It was super beneficial! I loved hearing about your experiences.<br><br>')
  .typeString('2. Well, as I was sending my first email, I wanted to be very professional and respectful. And while I will obviously maintain the latter, I will DEFINITELY be replying with lots of energy and excitement. Expect lots of stories in the future with LOTS of details! I LOVE the high energy and look forward to your next email. Even if it is "short", at least by our measure.<br><br>')
  .typeString('3. Well, having only received one email thus far, we shall see what happens haha!<br><br>')
  .typeString('4. Since you so kindly offered.<br><br>')
  .typeString('AHHHHHHH FINALS ARE KILLING ME! I AM VERY STRESSED. PROJECTS ON PROJECTS. AND WHEN I FINISH ONE PROJECT, ONTO THE NEXT PROJECT. DID I MENTION I HAVE ALL PROJECT BASED CLASSES? AHHHHHHHH! THIS WEEK CANNOT GO BY ANY FASTER. IS THIS EMAIL A RESULT OF ME PROCRASTINATING A PROJECT? WHO KNOWS?<br><br>')
  .typeString('In conclusion, I appreciate your openness. As a kid, on my soccer team, I never really cared if I was best friends with my teammates. But when my mother would tell me that their parents loved me?? I would be THRILLED. I always felt like I had an "old soul", I enjoy board games more than the average college student - Rummikub is my personal favorite. Anyways, getting sidetracked, I appreciate you sharing your story and being GENUINE. As someone who has always felt like I could carry a conversation with adults rather than my peers, I feel like we will be very good friends LOL! Very obviously, I have learned to be better at socializing with kids my age LOL! As I grow into adulthood, it does not seem too different. Simply more responsibility, more appreciation for the little things in life. Still scary though.<br><br>')
  .typeString('I hope to hear from you soon! Although, I made you wait a while, I hope you feel inclined to respond soon! Hope things are going well on the "left coast". Things are crazy over here on the "right coast"?<br><br>')
  .typeString('If this email makes no sense, I blame finals.<br><br>')
  .typeString('In LFS,<br><br>')
  .typeString('Emily Dinh :-)<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Dec 11, 2020, 2:01PM</div><br>')
  .pauseFor(300)
  .typeString('Emily!<br><br>')
  .typeString('AHHHHHHHHHHHHHHHHHHHHHH!!!!<br><br>')
  .typeString('My turn. ;-) Reciprocal to your present stress. I helped conduct a class in Europe time this week, which is so exhausting (1AM -9AM) California time. And as oft happens in the corporate world, I had to to present content that I am not entirely up to speed on... such that if one has not looked at it in awhile, it drips out of ones brain like melted chocolate chips in a fresh out of the oven  Christmas cookie that one had held in ones hand for too long.... or something like that.<br><br>')
  .typeString('Ok that is not such a great analogy.  I would eat the Christmas cookie long before it even had a chance to melt in my hand. Come to think of it, I would have finished three or four cookies...<br><br>')
  .typeString('IN ANY CASE.. you get the point.  As you were cramming for exams, I was cramming to do several hours worth of presenting, pretending to know what I am talking about... OR at least projecting that I do. HA HA!<br><br>')
  .typeString('Wait, along those lines.....story time:<br><br>')
  .typeString('In 1997, I was  a computer geek at NASD(AQ)  and went on one of my first corporate trips from DC to our Philadelphia office to do a major computer upgrade/migration.  On the VERY first desktop computer I went to upgrade, something really weird happened,  and I brought the entire office  down by crashing the main server.  I had NO CLUE what was going on.  I was able to recover the office server and get all the lawyers and analysts back up.  BUT as soon as I went to do another upgrade, BOOM!  Same thing.  Oh shiiiiiiitttt!!!<br><br>')
  .typeString('So here I was with a lot of unhappy people looking at me like "And YOU are our computer guy?!?!!"  Fortunately I had turned on my "treat people right"  extroverted side in the office long before I started doing the techincal work. Good lesson in working with fellow humans (another story for another day...) that gave me some social capital to work with while I called the home office in Maryland and reported the problem to my boss, and my bosss boss. WITH a little bit of panic I might add. They realized I was not crazy and that there was something going on that was quite strange. And even they with their experience and expertise did not have a clue. But I did not know that at the time. So my bosss boss, a great guy named Len, said QUITE EMPHATICALLY on his speaker phone:<br><br>')
  .typeString('"Now this is what I want you to do, Hans!"<br><br>')
  .typeString('"Yes Len?" I waited anxiously for highly technical direction from my bosss boss.<br><br>')
  .typeString('"I want you to EXUDE confidence!"<br><br>')
  .typeString('(awkward pause)<br><br>')
  .typeString('"Um.. OK"<br><br>')
  .typeString('(pause)<br><br>')
  .typeString('And then LAUGHING! As it dawned on me what he was asking me to do and why. He needed me to simply keep the people in the office in a state of calm and control, with me being the point guy, so he and the others could figure out what the hell was going on. If I could keep the calm on the front end, they could do the panicking on the back end and figure out what was going on.<br><br>')
  .typeString('Turns out the problem was a really weird technical thing that went deep into the servers network card configuration, such that a single setting caused it to crash when attached to a certain way by the very first upgraded desktop computer in the office.  The rest of them would have also crashed the server when upgraded. So it could have been a total nightmare.  PHEW!  I was able to get in, tweak it, and finish the upgrades in the week alotted.<br><br>')
  .typeString('To this day, Len and I , and our other friends, laugh about that story. I was just a young computer guy on one of his first BIG trips alone, and the first thing that happened was BOOM!, office down... my bad. Well not my bad, but perception by everyone else that it was my bad because I was the one who pushed the first button not knowing there was a hidden trap. And what is the first thing my  bosses boss told me to do? Not to find and fix the hidden trap, but to turn public perception from "my bad" to "I own this, will fix it, and make it work." Thereby buying time to do just that.<br><br>')
  .typeString('GO figure, a couple years later Len eventually convinced me to move out to California to join a startup named VMware. Been there ever since. :-)<br><br>')
  .typeString('***OK end of story. I was not going to tell a story because I GOTTA GET WORK DONE TODAY! But you  said it better first, "I am an EXTREME oversharer and talker"<br><br>')
  .typeString('I wanted to give you a reciprocal shout out and good energy to get through your stress. Mine is "over" for now, at least for the class. BUT now I have some deadlines to meet  before the holiday break. We get one at work too. WHOO HOO!<br><br>')
  .typeString('Stay tuned for more... :-)<br><br>')
  .typeString('GO EMILY!! GO ZETA BETA!!! AND GO HOKIES!!!<br><br>')
  .typeString('AND HAPPY HOKIE HOLIDAYS! :-D<br><br>')
  .typeString('Hans<br>')
  .typeString('"HOKIE Hans" :-D<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Dec 28, 2020, 5:16PM</div><br>')
  .pauseFor(300)
  .typeString('Hee Hee! I hope you liked that subject line Emily!<br><br>')
  .typeString('I still owe ya a response to your response making a response response thread, which noting our verbse propensities, already accounts for what most people would respond in a month of writing. HA!<br><br>')
  .typeString('OK FIRST ITEM:<br><br>')
  .typeString('I hope you got through finals with minimal stress and maximal grades. I have much I can say to wax poetic about finals and my college years of growth, failure, discovering APO and my true capabilities, and flying out of the ashes of failure like a fiery phoenix (or in my case like fiery rubber chicken ... HEE HEE!). BUT I will hold on that until your next finals. ;-)<br><br>')
  .typeString('IN THE MEANTIME IT IS TIME TO OVERWHELM YOU WITH A COMPLETE SUMMARY OF MY RECENT ACTIVITIES! IT HAS BEEN TOUGH KEEPING UP!<br><br>')
  .typeString('Brace yourself, it is story time! You may want to sit down for this. And consume it over the next week or so....<br><br>')
  .typeString('MERRY CHRISTMAS AND HAPPY NEW YEAR EMILY!!!!!<br><br>')
  .typeString('BIG HOLIDAY HUG and HAPPY NEW YEAR!<br><br>')
  .typeString('Your pal,<br><br>')
  .typeString('Chicken Man<br>')
  .typeString('aka Hans<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Jan 5, 2021, 10:35PM</div><br>')
  .pauseFor(300)
  .typeString('Dear Emily,<br><br>')
  .typeString('I am really behind in email again. And figured it would be good to tell you and that eventually I will catch up. So here goes:<br><br>')
  .typeString('Dear Emily,<br><br>')
  .typeString('I am really behind in email again. And figured it would be good to tell you and that eventually I will catch up. So here goes:<br><br>')
  .typeString('Dear Emily,<br><br>')
  .typeString('I am really behind in email again. And figured it would be good to tell you and that eventually I will catch up. So here goes:<br><br>')
  .typeString('Dear Emily,<br><br>')
  .typeString('I am really behind in email again. And figured it would be good to tell you and that eventually I will catch up. So here goes:<br><br>')
  .typeString('blablabla<br><br>')
  .typeString('OK OK you get the point. :-P :-)<br><br>')
  .typeString('Hope you are laughing!  HAPPY NEW YEAR!  From me and the squirrels on my back porch...<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Jan 5, 2021, 11:02PM</div><br>')
  .pauseFor(300)
  .typeString('Hi Hans,<br><br>')
  .typeString('First of all... THANK YOU for your wonderful Christmas email. It was extremely festive and my late reply is not representative of how impressed I was by your email LOL. The amount of effort and time invested is evident and extremely appreciated.<br><br>')
  .typeString('Last year, for some reason, it did not feel so festive but this year, I think I got my Christmas spirit back. Plus, after seeing a chicken travel around and talk to squirrels, how could I not be excited about the season.<br><br>')
  .typeString('Furthermore, I MUST comment on the speech bubbles and photography you have included in a previous email; if you ever become dissatisfied with your current career choice, it appears you have a future in graphic design as well.<br><br>')
  .typeString('This year, I truly felt like an adult, when asked what I wanted for Christmas, for some reason... they were all kitchen appliances. And the worst part??? I actually LOVED getting kitchen appliances for Christmas, I guess everyone has to grow up at some point right? Well, either way I am very content with my new Nespresso and SodaStream!<br><br>')
  .typeString('With this break, I have been lounging around the house, waking up late and taking naps despite the fact that I woke up late. So clearly..... very busy. But really, I am thankful for this break and the opportunity to catch my breath after a challenging semester. While I am nervous for the next semester, I am excited to continue as an artist and grow as an individual.<br><br>')
  .typeString('Hope you are well! Please disregard my lack and tardiness of responses, not ignoring you, simply trying to live a life worth discussing!!! LOL, be back with more news and stories I hope! Hope the holidays were good for you!<br><br>')
  .typeString('Sorry for the bad quality but enjoy this photo of a chocolate squirrel I got from my Trader Joes advent calendar LOL! Something about squirrels this season I guess.<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Feb 16, 2021, 4:52PM</div><br>')
  .pauseFor(300)
  .typeString('Just SAYIN HI!<br><br>')
  .typeString('And hoping your semester is going well!<br><br>')
  .typeString('Been a wee bit swamped. WHOO HOOO!<br><br>')
  .typeString('In any case, that does not mean I cannot send a short hello, even though my temptation is to send a novel!<br><br>')
  .typeString('HA! We need to write a book called, "The Book for People Who Write Novels Even When They Do Not Intend To!"<br><br>')
  .typeString('Here enjoy recent photos from a bike ride:<br><br>')
  .typeString('I call this my "Lunar New Year of the Ox Ride"  So visited some happy California cows and had a nice conversation with them.... (My company typically has a BIG celebration for Lunar New Year... a couple of years ago, I put my full chicken outfit on and was part of the show... Year of the Rooster! :-D)<br><br>')
  .typeString('BTW! Remember all year of the ox (YOTO), you can say "YOTO YOLO!" or "YOLO YOTO!" Feel free to get that out there. More folks need help to overcome their fears because YOLO, and then get things done like an Ox... YOTO!<br><br>')
  .typeString('Cheers and Chickens (I will still say that even though it is year of the Ox.) :-P ;-)<br><br>')
  .typeString('In LFS YOLO YOTO! :-D<br><br>')
  .typeString('Hans<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Mar 21, 2021, 5:41PM</div><br>')
  .pauseFor(300)
  .typeString('Hey Emily,<br><br>')
  .typeString('I am swamped! HA! Trying to keep up with it all. WHOO HOO!<br><br>')
  .typeString('SO doing the best thing and saying "HEY EMILY!!!" :-D and "HOPE YOU ARE DOING WELL!"<br><br>')
  .typeString('This will be one of my shortest emails ever! SHHHH DO NOT TELL ANYONE!<br><br>')
  .typeString('Happy SPRING! Here enjoy this little graphic I created of what happened in my back yard (no really!) :-)<br><br>')
  .typeString('Cheers and Chickens!<br><br>')
  .typeString('Hokie Hans<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Jun 20, 2021, 2:32PM</div><br>')
  .pauseFor(300)
  .typeString('EMILYYYYYYY!!<br><br>')
  .typeString('It is me! Crazy Zeta Beta Rubber Chicken Toting Hans!<br><br>')
  .typeString('Been ages, and I KNOW we have both been insanely busy in our respective universes... parallel dimensions... whatever.<br><br>')
  .typeString('Got up this morning and taking a respite to catch up with peeps! So consider yourself an APO Peep that is being caught up to, in a manner of speaking.<br><br>')
  .typeString('Contrary to our normal verbosity, I will leave it at that. HA!  Do not tell anyone I can be short and to the point.  Meh, they would not believe you anyway.<br><br>')
  .typeString('Hope you are well and have an awesome summer!<br><br>')
  .typeString('Cheers and Rubber Chickens!<br><br>')
  .typeString(':-D<br><br>')
  .typeString('Hokie Hans<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Jun 21, 2021, 1:52PM</div><br>')
  .pauseFor(300)
  .typeString('Hi Hans,<br><br>')
  .typeString('Nice to hear from you -- it has been awhile (though obviously no ones fault, life moves fast).<br><br>')
  .typeString('Since school has let out, I spent the first few weeks recuperating from junior year and the realization that I was over the halfway point in my college career. I lounged around the house and even began running as a hobby -- or more like a way to stay occupied and healthy. However, I have now begun working at a small, local gelato shop for the summer, which takes up most of my time. I love being home and being with my family; being at school five hours away for most of the year definitely takes its toll.<br><br>')
  .typeString('Thank you for your email and hope to hear from you soon! Hope the weather on the west coast is treating you well, it has been a super hot summer over here in VA (I have already burnt once this summer which is one time too many).<br><br>')
  .typeString('Enjoyed the toddler story thoroughly lol!<br><br>')
  .typeString('Lastly, sorry for my short email, not much going on in my life currently! And as school has let out, my brain does not function in the same way as it does from August to May!<br><br>')
  .typeString('Best,<br>')
  .typeString('Emily Dinh<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Jul 1, 2021, 1:32AM</div><br>')
  .pauseFor(300)
  .typeString('WHAT THE!<br><br>')
  .typeString('You responded 9 days ago!<br><br>')
  .typeString('Maybe I already told you one of my silly phrases. "Flies time, and then hit the windshield of life."<br><br>')
  .typeString('HA HA!<br><br>')
  .typeString('Ok I thought it was funny!<br><br>')
  .typeString('EMILYYYYYYY!<br><br>')
  .typeString(':-D<br><br>')
  .typeString('Good to hear back from you!<br><br>')
  .typeString('You make me laugh saying "Sorry for short email." We already touched base on the fact that our emails, our thought process, our style, our story telling can be epicly long. And yes the brain functions like different people, not just under stress of school and out of school, but in a 24 hour swing too!<br><br>')
  .typeString('As for the weather. It has been actually unseasonably cool here in the San Francisco Bay area, which, believe it or not, I am not entirely happy about. Not just because north of here is a devils inferno in the Pacific Northwest, and I am worried about everyone there, including all our furry friends. But also because, a little more selfishly, in my training for the upcoming deathride.com  (Yes you read that right), I need HEAT training, as it could be anywhere between freezing to 100+ degrees in the CA mountains throughout the day. So on the few days it HAS been hot here, 90 to 100+, I have been running or on my bike.  BUT, compared to VA, it is NOT the same because YOU have humidity! I remember that humidity, which can be brutal.<br><br>')
  .typeString('Heat aside, YAY you are taking up running!!!!<br><br>')
  .typeString('It is such an intellectual sport. I KID you not! It is a sport of the mind. Sound mind sound body sound mind.  Running has more than one primary purpose. Sure one is to stay in shape. The other is simply to think. Yes. Think.<br><br>')
  .typeString('I love telling the story of my coworker and friend, Tina, who is VERY intelligent and used to tell me she thought all the running I did was stupid. Yes true. And kinda funny in the development of our friendship. I kept telling her that most of the people in the running club were students or professors at Stanford, running having a special place for the mind. Finally one day she started run walk running. And then she got into running. But it gets better. At the same time I was travelling extensively for work, and falling into the corporate trap of too much travel, meetings, meals, alcohol, NOT running, and getting chubby. So I GOT TOTALLY OUT OF SHAPE while she was getting into shape. Keep in mind I used to be a competitive runner.<br><br>')
  .typeString('So one day I walked up to her at work and she said, in her high pitched Ukrainian accent, "Hans. You know that trail you told me about??"<br><br>')
  .typeString('I immediately predicted what she was about to tell me and responded, exasperated, "You ran up Black Mountain?" Black mountain trail is a 15 mile round trip with almost 3000 feet of climbing.<br><br>')
  .typeString('"Yes." she said with a smile.<br><br>')
  .typeString('"I HATE YOU!!!" I exclaimed!<br><br>')
  .typeString('We both laughed out loud. Here I was the runner of years, formerly competitive, and now fat. And here she was, the woman who said running was stupid, IN BETTER SHAPE than ME, and running insane runs up steep mountains that most people avoid.<br><br>')
  .typeString('Now she runs all the time and is happy! And we both love to tell people that story.<br><br>')
  .typeString('OK so I have attached a document. Take it however you will. It is totally unsolicited, so if you decide not to read it, no offense taken. I like to tell people I am full of unsolicited advice.<br><br>')
  .typeString('In the case of running, a friend years ago asked me for advice. So I typed up this document: "The Ultimate Workout Plan"<br><br>')
  .typeString('It has a lot of older references (I have a few gray hairs.. HEE HEE) you may or may not know of. BUT basically captures the intent, the game plan, the humor, and most importantly the joy of running, IMHO.<br><br>')
  .typeString('Maybe I will publish it one day. HA HA!<br><br>')
  .typeString('So yeah, RUN EMILY RUN!! GOOOO EMILY!!!!<br><br>')
  .typeString('And that is my response to you until we meet virtually again....<br><br>')
  .typeString('CHEERS AND RUBBER CHICKENS!<br><br>')
  .typeString('AND in LF&S,<br><br>')
  .typeString('Hans<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Oct 27, 2021, 3:10PM</div><br>')
  .pauseFor(300)
  .typeString('Hi Hans!<br><br>')
  .typeString('I hope you are doing well! It has been awhile but I figured I would send a short email (no, really, I mean short).<br><br>')
  .typeString('My "senior year" is off to a real difficult start, so I have had a lot less time to do social stuff. Even though I am only in 12 credits, I am struggling to find internships, schedule my classes, do homework, have time for a social life, etc. So I apologize for my lack of emails!<br><br>')
  .typeString('I hope everything is going well on the west coast! Better/more updates coming soon.<br><br>')
  .typeString('Best,<br>')
  .typeString('Emily Dinh<br><br>')
  .pauseFor(1000)
  .typeString('<div class="typed-out">Nov 2, 2021, 2:03AM</div><br>')
  .pauseFor(300)
  .typeString('EMILYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY!<br><br>')
  .typeString('I am doing well. Been sooooooooooooooooooooooooooooooo busy! As I know YOU have been too!<br><br>')
  .typeString('And I know we are both major story tellers, so get some serious cognitive dissonance if we send short emails. HA HA HA!<br><br>')
  .typeString('Absolutely NO worries!<br><br>')
  .typeString('Here have some positive energy sent from out here on the West Coast. YOU CAN DO IT! GET ER DONE!! Make the best of your "Senior year!!!!" "SQUEEZE the most out of your day!" is one of my mantras, especially when I have a ton to do.<br><br>')
  .typeString('****<br><br>')
  .typeString('Here is a random rubber chicken moment for a laugh. For Halloween I AGAIN practical joked a bunch of decorations around town by adding rubber chickens to them.  The neighbors know me as "Chicken Man" go figure! I also put various pumpkin heads on the "Plastic Peeps Protecting People". You know those short  yellow plastic dolls on the road that show motorists that kids are playing. (see photos below)<br><br>')
  .typeString('And if you want a GOOD laugh, watch these short  videos I posted over the last year for the holidays for neighbors.<br><br>')
  .typeString('OK I gotta get! Its 11:00 PM Pacific time. And I gotta get up at 5AM. YIKES! SQUEEZE the MOST out of your day!<br><br>')
  .typeString('Cheers, and Rubber Chickens!<br><br>')
  .typeString('Hans<br>')
  .typeString('VT EE ZB 93<br><br>')
  .pauseFor(1000)
  .start();
